name: Unity Linux CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.2.8f1]
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/checkout@v1
      with:
        repository: spatialos/gdk-for-unity-shared-ci
        ref: 16af8b4696032d897ba4d8075eaa61355f06f488
        path: ./shared-ci
    - run: bash ./ci/test.sh
