name: Unity Linux CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2019.2.8f1]
    
    steps:
    - uses: actions/checkout@v1
    - run: /opt/Unity/Editor/Unity -batchmode -nographics -silent-crashes -logFile -projectPath . -runEditorTests || exit 0
